### ISSUE TITLE
Don't claim that someone else's work is available under an MIT license

### ISSUE THREAD

**Issue by liampwll** [raulcorreia7/dota1x6_decompile#1]
It's debatable whether it's okay to upload this at all, but to claim that it's under an MIT license when no such license was attached to the original is incredibly shitty of you. If you are going to do this at least remove the license.

**Comment by raulcorreia7** [comment]
Hello liam!

This was a generic README.md template.
I think my intention was to attribute GPL2 LICENSE.

Might not be the very best at all, but at least people need to give him credits.
I'll update this soon

**Comment by liampwll** [comment]
By adding a license you're telling people they're free to use this under the terms of that license. Why put a license on this at all?

**Comment by raulcorreia7** [comment]
What do you suggest, no license?

**Comment by raulcorreia7** [comment]
I've changed the repo with no license with all credits or ownership falling under Xeno

**Comment by liampwll** [comment]
> What do you suggest, no license?

If you're going to upload it at all, yes. That way at the very least you won't have people assuming they're free to use the code and assets here.
